### PR TITLE
Remove need for Rust nightly and derive Default for Qid

### PR DESCRIPTION
**Pull request by lf94**
It would be extremely nice to have no reliance on Rust Nightly! This PR removes try_trait which is the only Nightly feature in use.

### CODE REVIEW

**Comment by lf94** [comment]
Closes https://github.com/pfpacket/rust-9p/issues/9

**Comment by pfpacket** [comment]
CI has failed. It looks like the build is broken on nightly.
The patch below will fix it.

```diff
diff --git a/src/srv.rs b/src/srv.rs
index 4e5a597e..fab1ed21 100644
--- a/src/srv.rs
+++ b/src/srv.rs
@@ -274,7 +274,7 @@ where
         let fids = fsfids.read().await;
         let get_fid = |fid: &u32| fids.get(fid).ok_or(error::Error::No(EBADF));
 
-        match msg.body {
+        let fut = match msg.body {
             Tstatfs { fid }                                                     => fs.rstatfs(get_fid(&fid)?),
             Tlopen { fid, ref flags }                                           => fs.rlopen(get_fid(&fid)?, *flags),
             Tlcreate { fid, ref name, ref flags, ref mode, ref gid }            => fs.rlcreate(get_fid(&fid)?, name, *flags, *mode, *gid),
@@ -304,7 +304,9 @@ where
             Tclunk { fid }                                                      => fs.rclunk(get_fid(&fid)?),
             Tremove { fid }                                                     => fs.rremove(get_fid(&fid)?),
             _                                                                   => return Err(error::Error::No(EOPNOTSUPP)),
-        }.await?
+        };
+
+        fut.await?
     };
 
     /* Drop the fid which the Tclunk contains */
```

**Comment by pfpacket** [comment]
> CI has failed. It looks like the build is broken on nightly.
The patch below will fix it.

Fixed in https://github.com/pfpacket/rust-9p/commit/08ebf56b38e164c4ceb86908d7762cb360e5fa4d

Could you rebase?

**Comment by lf94** [comment]
Yep, no problem @pfpacket !

I wanted to ask too: is there a reason for not supporting vanilla 9p2000? For my first play with 9p with Rust I'm going to use 9p2000.L because that's what this supports, but after I'm going to try with regular 9p2000. I saw in the source possible support for this, but a lot of it commented out?

**Comment by lf94** [comment]
@pfpacket rebased.

**Comment by lf94** [comment]
This includes the derivation for Default as well. Sorry it wasn't on a separate branch.

**Comment by lf94** [comment]
For tracking: closes #13

**Comment by pfpacket** [comment]
Thanks!

**Pull request merged**
